// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covenant.API.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for DotNetVersion.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DotNetVersion
    {
        [EnumMember(Value = "Net35")]
        Net35,
        [EnumMember(Value = "Net45")]
        Net45,
        [EnumMember(Value = "Net48")]
        Net48,
        [EnumMember(Value = "NetCore31")]
        NetCore31
    }
    internal static class DotNetVersionEnumExtension
    {
        internal static string ToSerializedValue(this DotNetVersion? value)
        {
            return value == null ? null : ((DotNetVersion)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this DotNetVersion value)
        {
            switch( value )
            {
                case DotNetVersion.Net35:
                    return "Net35";
                case DotNetVersion.Net45:
                    return "Net45";
                case DotNetVersion.Net48:
                    return "Net48";
                case DotNetVersion.NetCore31:
                    return "NetCore31";
            }
            return null;
        }

        internal static DotNetVersion? ParseDotNetVersion(this string value)
        {
            switch( value )
            {
                case "Net35":
                    return DotNetVersion.Net35;
                case "Net45":
                    return DotNetVersion.Net45;
                case "Net48":
                    return DotNetVersion.Net48;
                case "NetCore31":
                    return DotNetVersion.NetCore31;
            }
            return null;
        }
    }
}
